_BASE_: "base.yaml"
MODEL:
  DQRF_DETR:
    AUX_LOSS: False
    NUM_CLASSES: 1
    NUM_QUERIES: 300
    DENSE_QUERY: False
    RECTIFIED_ATTENTION: True

OUTPUT_DIR: "./datasets/train_model/crowdhuman/deform_detr_baseline"